# Generated by Django 4.1.7 on 2023-02-17 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hymnary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HymnarySong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('hymnary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hymnary_songs', to='core.hymnary')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_hymnaries', to='api.song')),
            ],
        ),
        migrations.AddField(
            model_name='hymnary',
            name='songs',
            field=models.ManyToManyField(related_name='hymns', through='core.HymnarySong', to='api.song'),
        ),
    ]
