# Generated by Django 4.1.4 on 2023-02-07 17:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_categories_songs_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hymns',
            new_name='Hymnaries',
        ),
    ]
