# Generated by Django 4.1.6 on 2023-02-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0004_hymnarysong_alter_hymnary_songs'), ('core', '0005_remove_hymnary_songs')]

    dependencies = [
        ('core', '0003_rename_hymnaries_hymnary'),
        ('api', '0008_song_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HymnarySong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(auto_created=True, unique=True)),
                ('hymnary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hymnary')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.song')),
            ],
        ),
        migrations.RemoveField(
            model_name='hymnary',
            name='songs',
        ),
    ]
