# Generated by Django 4.0.4 on 2023-06-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hymnary_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hymnarysong',
            name='order',
            field=models.IntegerField(verbose_name='Ordem'),
        ),
    ]
