# Generated by Django 4.1.6 on 2023-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_song_video_url'),
        ('core', '0004_hymnarysong_alter_hymnary_songs_squashed_0005_remove_hymnary_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hymnary',
            name='songs',
            field=models.ManyToManyField(related_name='hymns', through='core.HymnarySong', to='api.song'),
        ),
    ]
