# Generated by Django 4.0.4 on 2023-09-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_song_lyrics'),
        ('core', '0006_hymnary_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hymnarysong',
            unique_together={('song', 'hymnary')},
        ),
    ]
