# Generated by Django 4.0.4 on 2023-09-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_hymnarysong_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hymnarysong",
            options={"ordering": ("order",)},
        ),
    ]
