# Generated by Django 4.0.4 on 2023-11-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_hymnarysong_options_alter_hymnary_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hymnary',
            name='updated',
            field=models.BooleanField(default=True, verbose_name='Atualizado'),
        ),
    ]
