# Generated by Django 4.1.7 on 2023-02-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='video_url',
            new_name='preview_url',
        ),
    ]
