# Generated by Django 4.1.4 on 2022-12-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='category',
            new_name='categories',
        ),
    ]
