# Generated by Django 4.1.7 on 2023-02-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_video_url_song_preview_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="artist",
            name="slug",
            field=models.CharField(max_length=32, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(max_length=32, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="song",
            name="lyrics_url",
            field=models.CharField(max_length=256, verbose_name="Link da letra"),
        ),
        migrations.AlterField(
            model_name="song",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="song",
            name="preview_url",
            field=models.CharField(max_length=256, verbose_name="Link do preview"),
        ),
        migrations.AlterField(
            model_name="song",
            name="slug",
            field=models.CharField(max_length=64, verbose_name="Slug"),
        ),
    ]
