# Generated by Django 4.0.4 on 2023-08-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_artist_name_alter_artist_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="lyrics",
            field=models.TextField(blank=True, verbose_name="Letra"),
        ),
    ]
