# Generated by Django 4.1.4 on 2022-12-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_songs_categories_songs_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='categories',
            new_name='category',
        ),
    ]
