# Generated by Django 4.1.6 on 2023-02-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_hymns_hymnaries'),
        ('api', '0004_rename_categories_songs_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
