# Generated by Django 4.1.6 on 2023-02-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_artists_artist_rename_categories_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='lyrics',
            new_name='lyrics_url',
        ),
    ]
