# Generated by Django 4.0.4 on 2023-09-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_song_lyrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="lyrics",
            field=models.TextField(auto_created=True, blank=True, verbose_name="Letra"),
        ),
    ]
