# Generated by Django 4.1.6 on 2023-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_song_lyrics_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video_url',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
